version: "3.9"

volumes:
  db_data:

services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
      - db_data:/app/db
    ports:
      - "5555:5000"
    networks:
      - app-network   

networks:
  app-network:
    driver: bridge
